version: '2'
services:
  DockerRegistry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:                                                  
      - /var/opt:/var/lib/registry  
      - ./certs:/certs                                                  

  DockerRegistryWeb:     
    restart: always
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 8080:80
    environment:
      ENV_DOCKER_REGISTRY_HOST: 45.32.35.230     
      ENV_DOCKER_REGISTRY_PORT: 5000
    links:
      - DockerRegistry:DockerRegistry

  MyNginx:
    ports:
      - 8282:80/tcp
      - 443:443/tcp 
    tty: true   
    image: nginx:1.13.5-alpine        
    working_dir: "/etc/nginx"                         
    volumes:                    
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/docker-registry.conf:/etc/nginx/docker-registry.conf
      - ./certs/domain.crt:/etc/ssl/certs/ssl.crt           
      - ./certs/domain.key:/etc/ssl/certs/ssl.key                                            
      - ./nginx/log:/var/log/nginx
      - ./user/docker-registry.htpasswd:/etc/nginx/docker-registry.htpasswd      
    links:                                     
      - DockerRegistry:DockerRegistry
